export default {
    /*导航开始*/
    "header0" : {
        cn : "开奖倒计时",
        en : "Lottery countdown",
        rus : "Обратный отсчет лотереи",
        kor : "",
        jpn : "賞金発表カウントダウン",
    },
    "header2" : {
        cn : "首页",
        en : "Home page",
        rus : "Главная страница",
        kor : "",
        jpn : "トップページ",
    },
    "header3" : {
        cn : "登录",
        en : "Log in ",
        rus : "Авторизация",
        kor : "",
        jpn : "登録",
    },
    "header4" : {
        cn : "宠物中心",
        en : "Pet Center",
        rus : "Питомник",
        kor : "",
        jpn : "ペットセンター",
    },
    "header5" : {
        cn : "狗市",
        en : "Marketplace",
        rus : "Рынок",
        kor : "",
        jpn : "DOGマーケット",
    },
    "header6" : {
        cn : "虚拟育场",
        en : "Virtual farm",
        rus : "Виртуальная ферма",
        kor : "",
        jpn : "仮想飼育場",
    },
    "header7" : {
        cn : "公告",
        en : "Annoucement",
        rus : "Объявление",
        kor : "",
        jpn : "公告",
    },
    "header8" : {
        cn : "邀请好友，赢取OGC",
        en : "Invite",
        rus : "",
        kor : "",
        jpn : "フレンド招待",
    },
    "header9" : {
        cn : "反馈",
        en : "Feedback",
        rus : "Обратная связь",
        kor : "",
        jpn : "フィードバック",
    },
    "header10" : {
        cn : "HelloDog是基于以太坊区块链的宠物狗养成游戏，集合了出生，拍卖，购买，寻偶，繁殖，赠送、开奖、兑奖、回收等众多精彩玩法。\n",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "header11" : {
        cn : "世界杯",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    /*导航结束*/
    /*页尾开始*/
    "footer0" : {
        cn : "我的HelloDog",
        en : "My HelloDog",
        rus : "Мой HelloDog",
        kor : "",
        jpn : "私のHellodog",
    },
    "footer1" : {
        cn : "关于我们",
        en : "About us",
        rus : "О нас",
        kor : "",
        jpn : "私たちについて",
    },
    "footer2" : {
        cn : "交易记录",
        en : "Transactions record",
        rus : "История транзакций",
        kor : "",
        jpn : "取引記録",
    },
    "footer3" : {
        cn : "白皮书",
        en : "White paper",
        rus : "Белая бумага",
        kor : "",
        jpn : "利用規約",
    },
    "footer4" : {
        cn : "宠物市场",
        en : "Pet Market",
        rus : "Рынок домашних животных",
        kor : "",
        jpn : "ペットマーケット",
    },
    "footer5" : {
        cn : "开发者日志",
        en : "Developer logs",
        rus : "Журналы разработчиков",
        kor : "",
        jpn : "開発者日誌",
    },
    "footer6" : {
        cn : "常见问题",
        en : "Frequently asked questions (FAQ)",
        rus : "Часто задаваемые вопросы (ЧаВО)",
        kor : "",
        jpn : "よくある質問",
    },
    "footer7" : {
        cn : "QQ群:547351294",
        en : "QQ Group:547351294",
        rus : "Группа в QQ: 547351294",
        kor : "",
        jpn : "QQグループ：547351294",
    },
    "footer8" : {
        cn : "关注我们：",
        en : "follow us:",
        rus : "Подписывайтесь на нас:",
        kor : "",
        jpn : "私たちに注目して",
    },
    /*页尾开始*/
    /*首页开始*/
    "index-tit":{
        cn : "首页",
        en : "Home Page",
        rus : "Главная страница",
        kor : "",
        jpn : "トップページ",
    },
    "index0" : {
        cn : "购宠有礼哦！",
        en : "Buy pet, get gift",
        rus : "Купи питомца, получи подарок",
        kor : "",
        jpn : "ペットの購入でプレゼントをゲットできますよ",
    },
    "index1" : {
        cn : "可收藏，可交易可领奖。",
        en : "Can be collected, traded and rewarded",
        rus : "Может быть собиано, продано и вознаграждено",
        kor : "",
        jpn : "コレクションできる、取引できる、受賞できる",
    },
    "index2" : {
        cn : "奖金池",
        en : "Bonus Pool",
        rus : "Бонусный пул",
        kor : "",
        jpn : "賞金プール",
    },
    "index3" : {
        cn : "蓄奖池",
        en : "Storage of Bonus Pool",
        rus : "Храненилище бонусного пула",
        kor : "",
        jpn : "貯金プール",
    },
    "index4" : {
        cn : "基于以太坊智能合约的大型多人养殖游戏",
        en : "Large multi-player breeding game based on Ethereum smart contracts",
        rus : "Большая многопользовательская игра, основанная на интеллектуальных контрактах Ethereum",
        kor : "",
        jpn : "イーサネットのスマート契約に基づくMMO育成ゲーム",
    },
    "index5" : {
        cn : "开始，旺旺旺！",
        en : "Start, be a lucky dogs owner",
        rus : "Начни играть и будь счастливым владельцем собак!",
        kor : "",
        jpn : "ゲーム開始、ワンワン！",
    },
    "index6" : {
        cn : "奖池说明",
        en : "Bonus Pool Description",
        rus : "Описание бонусного пула",
        kor : "",
        jpn : "賞金プール説明",
    },
    "index7" : {
        cn : "中奖名单",
        en : "Winners List",
        rus : "Список победителей",
        kor : "",
        jpn : "当選者リスト",
    },
    "index8" : {
        cn : "本期开奖为",
        en : "Сurrent draw is:",
        rus : "Текущий розыгрыш:",
        kor : "",
        jpn : "今期の当選は",
    },
    "index9" : {
        cn : "累计中奖者",
        en : "Total Winners",
        rus : "Всего победителей",
        kor : "",
        jpn : "累計当選者",
    },
    "index9-0" : {
        cn : "（位）",
        en : " (location)",
        rus : "(место нахождения)",
        kor : "",
        jpn : "",
    },
    "index10" : {
        cn : "历史中奖者",
        en : " Record of the Winners",
        rus : "История победителей",
        kor : "",
        jpn : "過去当選者記録",
    },
    "index11" : {
        cn : "奖项说明",
        en : "Awards description",
        rus : "Описание наград",
        kor : "",
        jpn : "賞金項目説明",
    },
    "index12" : {
        cn : "当期售价：",
        en : "Current Price",
        rus : "Текущая цена",
        kor : "",
        jpn : "当期売価",
    },
    "index13" : {
        cn : "创世规则",
        en : "Genesis Rules",
        rus : "Правила генезиса",
        kor : "",
        jpn : "ゲーム規則",
    },
    "index13-1" : {
        cn : "玩法规则",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "index14" : {
        cn : "开奖",
        en : "Lottery",
        rus : "Нарисуйте лотерею",
        kor : "",
        jpn : "発表",
    },
    "index15" : {
        cn : "",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "index16" : {
        cn : "Hello Dog特色",
        en : "Hello Dog features",
        rus : "Особенности Hello Dog",
        kor : "",
        jpn : "Hello　Dogの特徴",
    },
    "index16-0" : {
        cn : "我们起初是由0代狗狗与玩家们见面，玩家可通过繁殖获取更多的狗狗来参与抽奖，0代狗的繁殖散播出去的狗进行繁殖将会给与它的0代狗祖先一定的报酬。",
        en : "At first  players meet a 0-generation dogs. Players throw breeding can get more dogs to participate in the lottery. If a dog breeded by 0-generation dog breeds again, then its ancestor can obtain a certain amount of reward.",
        rus : "Сначала игроки встречают собак нулевого поколения. Игроки, путём разведения, могут получить больше собак для участия в лотерее. Если собака, разведённая собакой породы нулевого поколения, вновь заведёт потомство, то её предок может получить определенную сумму вознаграждения.",
        kor : "",
        jpn : "プレイヤーは0代のDogから始め、もっと多くのDogを繁殖することにより抽選が参加できます。0代から繁殖されたDogが繁殖を行うときに、0代Dogは一定的な報酬を貰えます。",
    },
    "index17" : {
        cn : "变异说明",
        en : "Description of Mutation",
        rus : "Описание мутаций",
        kor : "",
        jpn : "変異説明",
    },
    "index17-0" : {
        cn : "如果你繁殖出样子比较怪异的狗狗，那么恭喜您，官方将在月底进行变异的强制回收，你可收获大量的报酬哦！",
        en : "If you breed a dog that looks quite weird, then, congratulations! The officals at the end of the month will redeem mutated dogs, and you can earn a lot of rewards!",
        rus : "Если вы разводите собаку, которая выглядит довольно странно, то, поздравляю! Официальные лица в конце месяца выкуят мутировавших собак, и вы сможете заработать много наград!",
        kor : "",
        jpn : "少し変わったDogを繁殖しましたか？おめでとうございます。システムにより月末に変異品種の強制回収が行いますので、大量な報酬を手に入れますよ。",
    },
    "index18" : {
        cn : "奖金池说明",
        en : "Bonus Pool Description",
        rus : "Описание бонусного пула",
        kor : "",
        jpn : "賞金プール説明",
    },
    "index18-0" : {
        cn : "Hello Dog上线后我们会将大部分收益都分配到奖金池中，主要收益来自于玩家购买初代狗以出售、租借等手续费都将注入到奖金池中，并且保证这一切都是公平，公正的。",
        en : "After HelloDog goes online, we will transfer major income to the bonus pool. The main profit comes from the fact that the players purchase 0-generation dogs for sale, leasing, and other fees, which all will be injected into the bonus pool, and all of it is fair and just.",
        rus : "После того, как HelloDog выйдет в интернет, мы перечислим основной доход в бонусный пул. Основная прибыль исходит из того факта, что игроки покупают собак 0-го поколения для продажи, лизинга и других сборов, которые все будут честно и справедливо введены в бонусный пул.",
        kor : "",
        jpn : "Hellodogがオンラインした後、我々は収益金の大きい一部を賞金プールに入れます。収益金は主にプレイヤーが0代DOGを購入した後の売出及びレンタルなどに発生する手数料になります。",
    },
    "index19" : {
        cn : "蓄奖池说明",
        en : "Storage of Bonus Pool Description",
        rus : "Описание хранилища бонусного пула",
        kor : "",
        jpn : "貯金プールとは",
    },
    "index19-0" : {
        cn : "每一期开奖如无人中一等奖，我们将会从奖金池中抽取5%的资金注入到蓄奖池中，直到有人中一等奖并兑取为止，蓄奖池主要是为了当有一等奖得主获得奖金时，奖金池的奖金会迅速下降，为了弥补这块奖金我们根据当期中奖者的中奖金额适当的从蓄奖池中拿出部分奖金注入奖金池。",
        en : " If in each phase of lottery, no one wins the first prize, we will charge 5% of the fund from the bonus pool to the storage of bonus pool, until someone hits the first prize and cashes it. A storage of bonus pool setted mainly for: when the prize winner obtains reward, the money of the bonus pool rapidly declines, so to offset that amount, we according to the winned prize in current lottery, extract respective amount of money from storage of bonus pool into the bonus pool.",
        rus : "Если на каждом этапе лотереи никто не выигрывает первый приз, мы будем начислять 5% от фонда бонусного пула в хранилище бонусного пула, пока кто-то не победит и не выиграет приз. Хранилище бонусного пула, созданно главным образом для: когда победитель получает награду, количество денег в бонусном пуле быстро снижается, поэтому, чтобы компенсировать эту сумму, мы, согласно выигрышному призу в текущей лотерее, извлекаем соответствующую сумму денег из хранилища бонусного пула в бонусный пул.",
        kor : "",
        jpn : "一等賞が当選されない場合、当期の賞金プールから5%の資金を取り出し、貯金プールに入れます。一等賞が当選されるまで、毎期同じことを繰り返します。一等賞が当選されると賞金プールの資金は大幅に減少しますので、その金額によって貯金プールから資金を取り出して減少した賞金を補充することが出来ます。",
    },
    "index20" : {
        cn : "我单纯是收藏品吗？",
        en : "Am I simply a collector?",
        rus : "Разве я просто коллекционер?",
        kor : "",
        jpn : "僕は単純なコレクションですか",
    },
    "index20-0" : {
        cn : "什么！你居然就这么简单的认为我是收藏品？那狗狗我就不开心了，作为区块链这么多项目脱颖而出的产品，我不单单可以提升自我价值，还能让狗狗价值更高，并且，我！还！能！兑！奖！没错，我能够赚钱！我爱钱，希望拥有我的你和我一样也爱钱，但这也需要一点点运气，哈哈哈~",
        en : "What! You think I'm just a collectior? Then, my lovely dog, I'm not happy at all. Being the one who stands out from such lots of DAPPs of blockchain, I can not only promote my self-worth, but also make you more valuable, and I! Also! Can! Win! the! Prize! Yes, I can make money! I love money, I want you to love money as much as I do, but it also needs a bit of luck, hahaha ~",
        rus : "Что! Ты думаешь, что я просто коллекционер? Тогда, моя прекрасная собака, я совсем не доволен. Будучи тем, кто выделяется из такого количества децентрализованных приложений блокчейна, я могу не только повысить свою самооценку, но и сделать вас более ценным, и Я! Также! Могу! Выиграть! Приз! Да, я могу заработать деньги! Я люблю деньги, и я хочу, чтобы вы любили деньги так же, как и я, но также нужно немного удачи, хахаха ~",
        kor : "",
        jpn : "何？そんなに簡単に僕のことをコレクションと思ってるの？ショックだワン…ブロックチェーンの多くのプロジェクトから選ばれた優秀な製品として、僕は単なるプレイヤーの自己価値をアップすることができるだけではなく、DOG達の価値も高める事ができますワン。そして、賞金に当たれます！その通り、僕は稼げます！僕はお金大好きだワン。僕の飼い主の貴方も同じようにお金大好きになってほしいワン。まぁ、もちろん、運も必要だな！ハハ～",
    },
    "index21" : {
        cn : "开始汪汪汪",
        en : "Start!Woof, woof ,woof!",
        rus : "Старт! Ух, ух, ух!",
        kor : "",
        jpn : "ゲーム開始！ワンワン",
    },
    "index22" : {
        cn : "<span> placeholder1 </span><span>获得了</span><span> placeholder2 ETH</span>",
        en : "<span> placeholder1 </span><span>Obtained</span><span> placeholder2 ETH</span>",
        rus : "",
        kor : "",
        jpn : "",
    },
    "index23" : {
        cn : "时",
        en : "h",
        rus : "",
        kor : "",
        jpn : "",
    },
    "index24" : {
        cn : "分",
        en : "m",
        rus : "",
        kor : "",
        jpn : "",
    },
    "index25" : {
        cn : "秒",
        en : "s",
        rus : "",
        kor : "",
        jpn : "",
    },
    "index25" : {
        cn : "秒",
        en : "s",
        rus : "",
        kor : "",
        jpn : "",
    },
    "index26" : {
        cn : "累积分红：",
        en : "Dividend:",
        rus : "",
        kor : "",
        jpn : "",
    },
    "index27" : {
        cn : "今日0代分红：",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    /*首页结束*/

    /*创世规则开始*/
    "awardExplain0":{
        cn: "创世狗共有两只，它不能参与抽奖、繁殖，创世狗起始价格由官方制定，每次购买的价格是上一个拥有者购买价格的两倍。官方将分得出售价格的20%手续费，奖金池收取3.75%手续费。",
        en : "There are two Genesis dogs in total, they cannot participate in prize drawing and breeding, the prices of Genesis dogs are set by the game developer, the price of each purchase of a Genesis dog is the double of the price the previous owner paid. The official fee will be 20% of the selling price, and the fee will be 3.75%",
        rus : "",
        kor : "",
        jpn : "",
    },
    "awardExplain1":{
        cn: "创世狗相当于Hello Dog的股东制，所有狗狗繁殖每只创世狗将分得手续费0.001ETH。",
        en : "Genesis Dogs is equivalent to the shareholder system of Hello Dog. All breeders will receive a 0.001 ETH fee for each creation dog.",
        rus : "",
        kor : "",
        jpn : "",
    },
    /*创世规则结束*/

    /*历史记录开始*/
    "history-title":{
        cn:"历史中奖者",
        en : "Record of the Winners",
        rus : "История победителей",
        kor : "",
        jpn : "過去当選者記録",
    },
    "history0":{
        cn:"输入开奖期号",
        en : "Enter period number of the lottery",
        rus : "Введите номер лотереи",
        kor : "",
        jpn : "抽選期番入力",
    },
    "history1":{
        cn:"搜索",
        en : "Search",
        rus : "Поиск",
        kor : "",
        jpn : "検索",
    },
    "history2":{
        cn:"期号",
        en : "Lottery Term",
        rus : "Лотерея",
        kor : "",
        jpn : "抽選期番入力",
    },
    "history3":{
        cn:"开奖时间",
        en : "Lottery Time",
        rus : "Время лотереи",
        kor : "",
        jpn : "発表日時",
    },
    "history4":{
        cn:"中奖",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "history5":{
        cn:"中奖奖项",
        en : "Lottery Prizes",
        rus : "Призы лотереи",
        kor : "",
        jpn : "当選賞金項目",
    },
    "history6":{
        cn:"奖金",
        en : "Prize",
        rus : "Приз",
        kor : "",
        jpn : "賞金",
    },
    "history7":{
        cn:"中奖者",
        en : "Winners",
        rus : "Победители",
        kor : "",
        jpn : "当選者",
    },
    "history8":{
        cn:"",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    /*历史记录结束*/

    /*宠物市场开始*/
    "list0" : {
        cn : "出售",
        en : "On sale",
        rus : "В продаже",
        kor : "",
        jpn : "売出",
    },
    "list1" : {
        cn : "官方发布",
        en : "Official Release",
        rus : "Официальный релиз",
        kor : "",
        jpn : "公式発表",
    },
    "list2" : {
        cn : "所有",
        en : "All",
        rus : "Все",
        kor : "",
        jpn : "すべて",
    },
    "list3" : {
        cn : "总数",
        en : "Total",
        rus : "Всего",
        kor : "",
        jpn : "合計数",
    },
    "list4" : {
        cn : "排序",
        en : "Rank",
        rus : "Ранг",
        kor : "",
        jpn : "並べ替え",
    },
    "list5" : {
        cn : "价格从高到低",
        en : "Price from High to Low",
        rus : "Цена от высокой к низкой",
        kor : "",
        jpn : "価額が高い順",
    },
    "list5-1" : {
        cn : "代数从高到低",
        en : "Generation from High to Low",
        rus : "Поколение от высокого до низкого",
        kor : "",
        jpn : "代数が高い順",
    },
    "list5-2" : {
        cn : "价格从低到高",
        en : "Price from low to high",
        rus : "",
        kor : "",
        jpn : "",
    },
    "list5-3" : {
        cn : "代数从低到高",
        en : "gen from low to high",
        rus : "",
        kor : "",
        jpn : "",
    },
    "list5-4" : {
        cn : "ID从高到低",
        en : "ID from high to low",
        rus : "",
        kor : "",
        jpn : "",
    },
    "list5-5" : {
        cn : "ID从低到高",
        en : "ID from low to high",
        rus : "",
        kor : "",
        jpn : "",
    },
    "list6" : {
        cn : "等待领养",
        en : "Wait for adopting",
        rus : "Ожидание усыновления",
        kor : "",
        jpn : "引取待ち",
    },
    "list7" : {
        cn : "代",
        en : "Generation",
        rus : "Поколение от высокого до низкого",
        kor : "",
        jpn : "代",
    },
    "list8-0" : {
        cn : "神速",
        en : "Speedy",
        rus : "Стремительный",
        kor : "",
        jpn : "神スピード",
    },
    "list8-1" : {
        cn : "急速",
        en : "Rapid",
        rus : "Скорый",
        kor : "",
        jpn : "急速",
    },
    "list8-2" : {
        cn : "快速",
        en : "Fast",
        rus : "Быстрый",
        kor : "",
        jpn : "快速",
    },
    "list8-3" : {
        cn : "中速",
        en : "Medium speed",
        rus : "Средняя скорость",
        kor : "",
        jpn : "半速",
    },
    "list8-4" : {
        cn : "慢速",
        en : "Plodding",
        rus : "Неторопливый",
        kor : "",
        jpn : "スロースピード",
    },
    "list8-5" : {
        cn : "迟缓",
        en : "Slow",
        rus : "Медленный",
        kor : "",
        jpn : "ゆっくり",
    },
    "list8-6" : {
        cn : "龟速",
        en : "Sluggish",
        rus : "Вялый",
        kor : "",
        jpn : "亀スピード",
    },
    "list8-7" : {
        cn : "昏迷",
        en : "Numb",
        rus : "Оцепенелый",
        kor : "",
        jpn : "気絶",
    },
    "list9" : {
        cn : "升序",
        en : "Ascending Order",
        rus : "В порядке возрастания",
        kor : "",
        jpn : "昇順",
    },
    "list10" : {
        cn : "降序",
        en : "Descending Order",
        rus : "В порядке убывания",
        kor : "",
        jpn : "降順",
    },
    "list11" : {
        cn : "天",
        en : "Day",
        rus : "День",
        kor : "",
        jpn : "日",
    },
    "list12" : {
        cn : "小时",
        en : "Hour",
        rus : "Час",
        kor : "",
        jpn : "時間",
    },
    "list13" : {
        cn : "分钟",
        en : "Minute",
        rus : "Минута",
        kor : "",
        jpn : "分",
    },
    "list14-0" : {
        cn : "休息中",
        en : "Resting",
        rus : "В покое",
        kor : "",
        jpn : "休憩中",
    },
    "list14-1" : {
        cn : "等待领养",
        en : "Waiting for adoption",
        rus : "Ожидание усыновления",
        kor : "",
        jpn : "引取待ち",
    },
    "list14-2" : {
        cn : "等待育种",
        en : "Want to sire",
        rus : "",
        kor : "",
        jpn : "子作り待ち",
    },
    "list14-3" : {
        cn : "怀孕中",
        en : "Waiting for breeding",
        rus : "Ожидание размножения",
        kor : "",
        jpn : "妊娠中",
    },
    "list14-4" : {
        cn : "已被系统回收",
        en : "Have been recycled by the system",
        rus : "Переработано системой",
        kor : "",
        jpn : "回収されました",
    },
    "list15" : {
        cn : "",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "list16" : {
        cn : "页码只能输入大于1的正整数",
        en : "Only positive integers greater than 1 can be inputted in page number.",
        rus : "В число страниц могут вводиться только положительные целые числа, превышающие 1.",
        kor : "",
        jpn : "ページコードは1より大きい整数しか入力できません。",
    },
    "list17" : {
        cn : "没有这么多页",
        en : "There are no so many pages.",
        rus : "Такое количество страниц не существует.",
        kor : "",
        jpn : "ページ存在しません",
    },
    "list18" : {
        cn : "提示: 操作成功后，矿工会进行挖矿，这个时间需要用户耐心等待，挖矿成功后刷新页面即可显示。",
        en : "Tip: After the operation is completed successfully, the miner(s) will start mining. Please be patient during this time. After the successful mining, you can refresh the page and it will be displayed.",
        rus : "Совет. После успешного завершения операции, майнер начнет майнинг. Пожалуйста, будьте терпеливы в это время. После успешного майнинга вы можете обновить страницу, и он будет отображаться.",
        kor : "",
        jpn : "注意：操作成功後に、鉱夫は掘削し始めます。少し時間をかかりますので、暫くお待ちください。掘削が成功した後、ページを更新すると表示されます。",
    },
    "list19" : {
        cn : "变异",
        en : "Variation",
        rus : "",
        kor : "",
        jpn : "変異",
    },
    "list20" : {
        cn : "创世狗",
        en : "Genesis Dog",
        rus : "Перворождённая Собака",
        kor : "",
        jpn : "創世DOG",
    },
    "list21" : {
        cn : "ID搜索",
        en : "ID search",
        rus : "ID Поиск",
        kor : "",
        jpn : "ID 検索",
    },
    "list22" : {
        cn : "赞",
        en : "Like",
        rus : "",
        kor : "",
        jpn : "",
    },
    /*宠物市场结束*/

    /* 宠物详情开始 */
    "petInfo-title" : {
        cn : "宠物详情",
        en : "Pet details",
        rus : "Информация о домашнем питомце",
        kor : "",
        jpn : "ペット詳細終了",
    },
    "petInfo-title1" : {
        cn : "宠物繁殖",
        en : "Pet breeding",
        rus : "Разведение питомца",
        kor : "",
        jpn : "",
    },
    "petInfo1" : {
        cn : "宠物市场",
        en : "Pets trading market",
        rus : "Рынок домашних животных",
        kor : "",
        jpn : "ペットマーケット",
    },
    "petInfo2" : {
        cn : "售价",
        en : "Price",
        rus : "Цена",
        kor : "",
        jpn : "売価",
    },
    "petInfo3" : {
        cn : "代狗",
        en : "Gen",
        rus : "Поколение собаки",
        kor : "",
        jpn : "代DOG",
    },
    "petInfo4" : {
        cn : "休息时间",
        en : "Rest time",
        rus : "Время отдыха",
        kor : "",
        jpn : "休憩時間",
    },
    "petInfo4-1" : {
        cn : "当一只狗狗与另一只狗狗育种之后，在短时间内它将暂时无法再次育种，狗狗每经过一次育种，其所需的冷却时间也将增加。",
        en : "When a dog had bred with another dog, it will not be able to breed again in a short time. The cooldown time required for next breeding will increase.",
        rus : "Если собака была разведена с другой собакой, она не сможет размножаться снова в течение короткого времени. Время перезарядки, необходимое для следующего размножения, будет увеличиваться.",
        kor : "",
        jpn : "DOGは一回子作りした後暫くの間に再度の子作りが出来ません。子作り回数が増えますと、クーリング時間も長くなります。",
    },
    "petInfo4-2" : {
        cn : "神速",
        en : "Speedy",
        rus : "Стремительный",
        kor : "",
        jpn : "神スピード",
    },
    "petInfo4-3" : {
        cn : "急速",
        en : "Rapidly",
        rus : "Скорый",
        kor : "",
        jpn : "急速",
    },
    "petInfo4-4" : {
        cn : "快速",
        en : "Fast",
        rus : "Быстрый",
        kor : "",
        jpn : "快速",
    },
    "petInfo4-5" : {
        cn : "中速",
        en : "Medium speed",
        rus : "Средняя скорость",
        kor : "",
        jpn : "半速",
    },
    "petInfo4-6" : {
        cn : "慢速",
        en : "Plodding",
        rus : "Неторопливый",
        kor : "",
        jpn : "スロースピード",
    },
    "petInfo4-7" : {
        cn : "迟缓",
        en : "Slow",
        rus : "Медленный",
        kor : "",
        jpn : "ゆっくり",
    },
    "petInfo4-8" : {
        cn : "龟速",
        en : "Sluggish",
        rus : "Вялый",
        kor : "",
        jpn : "亀スピード",
    },
    "petInfo4-9" : {
        cn : "昏迷",
        en : "Numb",
        rus : "Оцепенелый",
        kor : "",
        jpn : "気絶",
    },
    "petInfo4-10" : {
        cn : "分钟",
        en : "Minute",
        rus : "Минута",
        kor : "",
        jpn : "分",
    },
    "petInfo4-11" : {
        cn : "小时",
        en : "Hour",
        rus : "Час",
        kor : "",
        jpn : "時間",
    },
    "petInfo4-12" : {
        cn : "天",
        en : "Day",
        rus : "День",
        kor : "",
        jpn : "日",
    },
    "petInfo5" : {
        cn : "虚拟交配",
        en : "Virtual mating",
        rus : "Виртуальное спаривание",
        kor : "",
        jpn : "仮想交配",
    },
    "petInfo6" : {
        cn : "寄售",
        en : "Sale",
        rus : "Продажа",
        kor : "",
        jpn : "売出",
    },
    "petInfo6-1" : {
        cn : "购买",
        en : "Purchase",
        rus : "Покупка",
        kor : "",
        jpn : "購入",
    },
    "petInfo6-2" : {
        cn : "繁殖",
        en : "Breeding",
        rus : "Разведение",
        kor : "",
        jpn : "繁殖",
    },
    "petInfo6-3" : {
        cn : "寄售",
        en : "Sale",
        rus : "Продажа",
        kor : "",
        jpn : "売出",
    },
    "petInfo6-4" : {
        cn : "取消寄售",
        en : "Cancel Sale",
        rus : "Отменить продажу",
        kor : "",
        jpn : "売出取消",
    },
    "petInfo6-5" : {
        cn : "取消租借",
        en : "Cancel Renting",
        rus : "Отменить аренду",
        kor : "",
        jpn : "レンタル取消",
    },
    "petInfo6-6" : {
        cn : "购买价格",
        en : "Price",
        rus : "",
        kor : "",
        jpn : "",
    },
    "petInfo7" : {
        cn : "当前成交价",
        en : "Current Transaction Price",
        rus : "Текущая цена сделки",
        kor : "",
        jpn : "現在の取引価額",
    },
    "petInfo8" : {
        cn : "起始价格",
        en : "Initial Price",
        rus : "Начальная цена",
        kor : "",
        jpn : "最初売価",
    },
    "petInfo9" : {
        cn : "当前价格",
        en : "Current Price",
        rus : "Текущая цена",
        kor : "",
        jpn : "現在売価",
    },
    "petInfo10" : {
        cn : "结束价格",
        en : "Final Price",
        rus : "Итоговая цена",
        kor : "",
        jpn : "最終売価",
    },
    "petInfo11" : {
        cn : "宝石属性",
        en : "Gem attribute",
        rus : "Атрибут самоцвета",
        kor : "",
        jpn : "ダイヤ属性",
    },
    "petInfo11-0" : {
        cn : "我是变异狗",
        en : "I am a mutated dog",
        rus : "Я мутировавшая собака",
        kor : "",
        jpn : "僕は変異DOGです",
    },
    "petInfo12" : {
        cn : "父母",
        en : "Parents",
        rus : "Родители",
        kor : "",
        jpn : "お親",
    },
    "petInfo13" : {
        cn : "主人",
        en : "Owner",
        rus : "Владелец",
        kor : "",
        jpn : "飼い主",
    },
    "petInfo14" : {
        cn : "狗狗名称",
        en : "Names of Dogs",
        rus : "Имена собак",
        kor : "",
        jpn : "DOGの名前",
    },
    "petInfo15" : {
        cn : "繁殖时间",
        en : "Breeding time",
        rus : "Время размножения",
        kor : "",
        jpn : "繁殖時間",
    },
    "petInfo16" : {
        cn : "号码：",
        en : "Number",
        rus : "Номер",
        kor : "",
        jpn : "番号",
    },
    "petInfo17" : {
        cn : "恭喜你，我是变异狗，我将会被定期回收，回收后我的主人将会平分总奖金池的3%！",
        en : "Congratulations! I am a mutated dog and I will be recylced at the end of each month. After the recycle, my owner will split 3% of the total bonus pool!  ",
        rus : "Поздравления! Я мутировавшая собака, и я буду перерабатываться в конце каждого месяца. После утилизации мой владелец разделит 3% от общего бонусного пула!",
        kor : "",
        jpn : "おめでとうございます。僕は変異DOGです。定期に回収されます。回収された後に飼い主は総合賞金プール資金の3％を等分できます。",
    },
    "petInfo18" : {
        cn : "",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    
    /* 宠物详情结束 */

    /* 宠物中心开始 */
    "petCenter-title" : {
        cn : "我的狗狗",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "petCenter1" : {
        cn : "更改",
        en : "Change",
        rus : "Изменение",
        kor : "",
        jpn : "修正",
    },
    "petCenter2" : {
        cn : "复制地址",
        en : "Copy an address",
        rus : "Копировать адрес",
        kor : "",
        jpn : "アドレスコピー",
    },
    "petCenter3" : {
        cn : "收益",
        en : "Income",
        rus : "Прибыль",
        kor : "",
        jpn : "収益",
    },
    "petCenter4" : {
        cn : "收益详情",
        en : "Income Details",
        rus : "Сведения о прибыли",
        kor : "",
        jpn : "収益詳細",
    },
    "petCenter5" : {
        cn : "个人中心",
        en : "Personal Center",
        rus : "Персональный центр",
        kor : "",
        jpn : "個人センター",
    },
    "petCenter6" : {
        cn : "交易记录",
        en : "Transactions Record",
        rus : "Запись транзакций",
        kor : "",
        jpn : "取引記録",
    },
    "petCenter7" : {
        cn : "兑奖记录",
        en : "Redemptions Record",
        rus : "Запись погашений",
        kor : "",
        jpn : "受賞記録",
    },
    "petCenter8" : {
        cn : "宠物",
        en : "Pet",
        rus : "Питомец",
        kor : "",
        jpn : "ペット",
    },
    "petCenter9" : {
        cn : "急速",
        en : "Rapid",
        rus : "Скорый",
        kor : "",
        jpn : "急速",
    },
    "petCenter10" : {
        cn : "转赠",
        en : "Gift",
        rus : "Подарок",
        kor : "",
        jpn : "プレゼント",
    },
    "petCenter11" : {
        cn : "交配",
        en : "Breeding",
        rus : "Разведение",
        kor : "",
        jpn : "交配",
    },
    "petCenter12" : {
        cn : "租借",
        en : "Rent",
        rus : "Аренда",
        kor : "",
        jpn : "レンタル",
    },
    "petCenter13" : {
        cn : "寄售",
        en : "Sale",
        rus : "Продажа",
        kor : "",
        jpn : "売出",
    },
    "petCenter13-1" : {
        cn : "禁止寄售",
        en : "Sale is forbidden",
        rus : "Продажа запрещена",
        kor : "",
        jpn : "売出禁止",
    },
    "petCenter14" : {
        cn : "兑奖",
        en : "Redemption of prize",
        rus : "Выкуп",
        kor : "",
        jpn : "受賞",
    },
    "petCenter14-1" : {
        cn : "一等奖",
        en : "First prize",
        rus : "Первый приз",
        kor : "",
        jpn : "一等賞",
    },
    "petCenter14-2" : {
        cn : "二等奖",
        en : "Second prize",
        rus : "Второй приз",
        kor : "",
        jpn : "ニ等賞",
    },
    "petCenter14-3" : {
        cn : "三等奖",
        en : "Third prize",
        rus : "Третий приз",
        kor : "",
        jpn : "三等賞",
    },
    "petCenter14-4" : {
        cn : "四等奖",
        en : "Fourth prize",
        rus : "Четвертый приз",
        kor : "",
        jpn : "四等賞",
    },
    "petCenter14-5" : {
        cn : "五等奖",
        en : "Fifth prize",
        rus : "Пятый приз",
        kor : "",
        jpn : "五等賞",
    },
    "petCenter14-6" : {
        cn : "六等奖",
        en : "Six prize",
        rus : "Шесть призов",
        kor : "",
        jpn : "六等賞",
    },
    "petCenter14-7" : {
        cn : "七等奖",
        en : "Seven prize",
        rus : "Семь призов",
        kor : "",
        jpn : "七等賞",
    },
    "petCenter15" : {
        cn : "空闲中",
        en : "Idle Time",
        rus : "Время простоя",
        kor : "",
        jpn : "空き中",
    },
    "petCenter16" : {
        cn : "代",
        en : "Generation",
        rus : "Поколение",
        kor : "",
        jpn : "代",
    },
    "petCenter17" : {
        cn : "请输入或粘贴需转赠的地址",
        en : "Please enter or paste the address to be transferred",
        rus : "Введите или вставьте адрес для передачи",
        kor : "",
        jpn : "送る宛先を入力或いは貼り付けをしてください",
    },
    "petCenter18" : {
        cn : "注意：为确保宠物能安全到达，请确保您的朋友有一个钱包地址。",
        en : "Attention: To ensure that the pets safely arrive, make sure your friend has a wallet address.",
        rus : "Внимание. Чтобы обеспечить безопасное прибытие домашних животных, убедитесь, что ваш друг имеет кошелек.",
        kor : "",
        jpn : "注意：ペットを無事に届くために、フレンドのウォレットアドレスを確認してください。",
    },
    "petCenter19" : {
        cn : "提交",
        en : "Submit",
        rus : "Отправить",
        kor : "",
        jpn : "提出",
    },
    "petCenter20" : {
        cn : "确定",
        en : "Confirm",
        rus : "Подтвердить",
        kor : "",
        jpn : "確認",
    },
    "petCenter21" : {
        cn : "钱包地址",
        en : "Wallet Address",
        rus : "Адрес кошелька",
        kor : "",
        jpn : "ウォレットアドレス",
    },
    "petCenter22" : {
        cn : "空闲中",
        en : "Available Now",
        rus : "На данный момент доступно",
        kor : "",
        jpn : "空き中",
    },
    "petCenter23" : {
        cn : "出售中",
        en : "On sale",
        rus : "В продаже",
        kor : "",
        jpn : "売出中",
    },
    "petCenter24" : {
        cn : "等待育种",
        en : "Wait for Breeding",
        rus : "Ожидайте разведения",
        kor : "",
        jpn : "子作り待ち",
    },
    "petCenter25" : {
        cn : "怀孕中",
        en : "During Pregnancy",
        rus : "В течение беремености",
        kor : "",
        jpn : "妊娠中",
    },
    "petCenter26" : {
        cn : "接生",
        en : "Give Birth",
        rus : "Рожать",
        kor : "",
        jpn : "助産",
    },
    "petCenter27" : {
        cn : "请先填写您朋友的以太坊钱包地址！",
        en : "Please enter the ethereum wallet address of your friend first！",
        rus : "Пожалуйста, сначала введите адрес Ethereum кошелька вашего друга!",
        kor : "",
        jpn : "まずフレンドのブロックチェーンアドレスを入力してください。",
    },
    "petCenter28" : {
        cn : "名称：",
        en : "Name：",
        rus : "Имя:",
        kor : "",
        jpn : "名称",
    },
    "petCenter29" : {
        cn : "代数：",
        en : "Gen:",
        rus : "Поколение:",
        kor : "",
        jpn : "代",
    },
    "petCenter30" : {
        cn : "状态：休息中",
        en : "Status: Resting",
        rus : "Статус: Отдых",
        kor : "",
        jpn : "状態：休憩中",
    },
    "petCenter31" : {
        cn : "状态：",
        en : "Status：",
        rus : "Статус:",
        kor : "",
        jpn : "状態：",
    },
    "petCenter32" : {
        cn : "育种狗狗",
        en : "Dog breeding",
        rus : "",
        kor : "",
        jpn : "",
    },
    "petCenter33" : {
        cn : "到狗市育种",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "petCenter34" : {
        cn : "与自己的狗狗繁殖",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "petCenter35" : {
        cn : "将被放到公共市场待人领养。狗狗出售价可在选定时间内上涨或下跌，出售时间结束后价格会保持稳定。只有取消销售才能将狗狗从狗市上收回。",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "petCenter36" : {
        cn : "提示：下拉刷新",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "petCenter37" : {
        cn : "收益记录",
        en : "Income Record",
        rus : "Отчёт о доходах",
        kor : "",
        jpn : "収益記録",
    },
    "petCenter38" : {
        cn : "提现记录",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "petCenter39" : {
        cn : "遛狗记录",
        en : "Record for walking the dog ",
        rus : "",
        kor : "",
        jpn : "犬を散歩させるレコード",
    },
    "petCenter40" : {
        cn : "一键遛狗",
        en : "One-button walk the dog",
        rus : "",
        kor : "",
        jpn : "ワンボタンで犬を散歩させる",
    },
    /* 宠物中心结束 */

    /*出售，租借上架开始*/
    "saleing0":{
        cn : "选择宠物",
        en : "Choose a Pet",
        rus : "Выберите питомца",
        kor : "",
        jpn : "ペット選択",
    },
    "saleing1":{
        cn : "给定价格",
        en : "Set a price",
        rus : "Назначьте цену",
        kor : "",
        jpn : "価額設定",
    },
    "saleing2":{
        cn : "上架完成",
        en : "On sale ",
        rus : "В продаже",
        kor : "",
        jpn : "出回り完了",
    },
    "saleing3":{
        cn : "起始价格",
        en : "Initial Price",
        rus : "Начальная цена",
        kor : "",
        jpn : "最初価額",
    },
    "saleing4":{
        cn : "结束价格",
        en : "Final Price",
        rus : "Итоговая цена",
        kor : "",
        jpn : "最終価額",
    },
    "saleing5":{
        cn : "期限出售",
        en : "Sales Term",
        rus : "Срок продажи",
        kor : "",
        jpn : "期限限定発売",
    },
    "saleing6":{
        cn : "天",
        en : "Day",
        rus : "День",
        kor : "",
        jpn : "日",
    },
    "saleing7":{
        cn : "完成",
        en : "Done",
        rus : "Завершено",
        kor : "",
        jpn : "完成",
    },
    "saleing8":{
        cn : "好的，让我们开始吧",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "saleing9":{
        cn : "好的，上架吧",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "saleing10":{
        cn : "出售狗狗",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    /*出售，租借上架结束*/

    /* 虚拟交配开始 */
    "mating1" : {
        cn : "您的两只狗狗很快就会成为狗父母！",
        en : "Two of your dogs will become parents soon.",
        rus : "Две твои собаки скоро станут родителями.",
        kor : "",
        jpn : "貴方様の2匹のDOGはもうすぐ親になりますよ",
    },
    "mating2" : {
        cn : "",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "mating3" : {
        cn : "注意：母系将获得新生宠物。",
        en : "Attention: The mother will get the newborn pet.",
        rus : "Внимание: мать скоро получит новорожденного.",
        kor : "",
        jpn : "注意：メスDOGはBABYDOGを所有します。",
    },
    "mating4" : {
        cn : "选择一只狗狗",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "mating5" : {
        cn : "仅展示符合虚拟交配条件的宠物",
        en : "Show the available pet for virtual mating.",
        rus : "Покажите доступное домашнее животное для виртуального спаривания.",
        kor : "",
        jpn : "仮想交配条件に合うペットだけ表示されます。",
    },
    "mating6" : {
        cn : "来，给它们点私人空间",
        en : "Come on, give them some privacy.",
        rus : "Ну же, дайте им чуточку личного пространства.",
        kor : "",
        jpn : "プライベートの空間をあげましょう",
    },
    "mating7" : {
        cn : "",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "mating8" : {
        cn : "没有合适的狗狗！",
        en : "No proper dog!",
        rus : "Нет подходящей собаки!",
        kor : "",
        jpn : "条件に合うDOGが見つかりませんでした。",
    },
    "mating9" : {
        cn : "请先选择狗狗的配偶",
        en : "Please choose a mate for your dog！",
        rus : "Пожалуйста, выберите партнёра для вашей собаки!",
        kor : "",
        jpn : "DOGの相手を選んでください。",
    },
    "mating10" : {
        cn : "繁殖价格",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "mating11" : {
        cn : "",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "mating12" : {
        cn : "您的狗狗",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "mating13" : {
        cn : "会产生狗宝宝。",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "mating14" : {
        cn : "将是狗爸爸。",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "mating15" : {
        cn : "好的，开始吧",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "mating16" : {
        cn : "按下面的按钮，您的两只狗狗将繁殖，后代出生后将会属于您。",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "mating17" : {
        cn : "请选择您的另一只狗狗作为狗妈妈！",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    
    /* 虚拟交配结束 */

    /*收益开始*/
    "earning-tit" :{
        cn : "收益记录",
        en : "Income Record",
        rus : "Отчёт о доходах",
        kor : "",
        jpn : "収益記録",
    },
    "earning0" :{
        cn : "0代狗繁殖散播的狗，如作为母系繁殖将获得一定利益收成。您的0代狗子孙如有中奖，您将会获得中奖金额的5%作为您的回报。",
        en : "Dogs reproduced by the gen 0  which breed as maternal will gain certain benefits. If you have a winner descendant of your gen 0 dog, you will receive 1% of the winning amount as reward.",
        rus : "",
        kor : "",
        jpn : "0代DOGから繁殖したDOGは、メスとして繁殖を行う場合、一定額の収益を貰えます。貴方様の0代DOGの子孫は賞金に当選した場合、貴方様も賞金額の1%を貰えます。",
    },
    "earning1" :{
        cn : "收益",
        en : "Income",
        rus : "Доход",
        kor : "",
        jpn : "収益",
    },
    "earning1-1" :{
        cn : "0代",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "earning2" :{
        cn : "回报",
        en : "Reward",
        rus : "Вознаграждение",
        kor : "",
        jpn : "返金",
    },
    "earning3" :{
        cn : "回收",
        en : "Recycling",
        rus : "Переработка",
        kor : "",
        jpn : "回収",
    },
    "earning4" :{
        cn : "您的0代狗ID placeholder1 作为母狗ID placeholder2 的祖先，繁殖出新生一代获得了 placeholder3 ETH收益！",
        en : "Your 0-generation dog ID placeholder1 was the ancestor of ID placeholder2 and bred the new generation to get a reward in ETH for placeholder3.",
        rus : "Ваша собака нулевого поколения была предком placeholder2 и развела новое поколение, чтобы получить вознаграждение в эфирах от placeholder3.",
        kor : "",
        jpn : "貴方の0代DOG（ID） placeholder1 はメスDOG（ID） placeholder2 の祖先として、新生DOG繁殖成功の placeholder3 ETH収益を貰いました。",
    },
    "earning4-0" :{
        cn : "您在 placeholder1 提现了 placeholder2 ETH",
        en : "You have withdrawn placeholder2 ETH at placeholder1",
        rus : "",
        kor : "",
        jpn : "あなたは placeholder1 に placeholder2 ETHを见ています。",
    },
    "earning5" :{
        cn : "您的0代狗ID placeholder1 作为ID  placeholder2 的祖先，ID  placeholder2 成功兑奖了 placeholder3 等奖，你将获得 placeholder4 ETH收益！",
        en : "Your 0-generation dog ID placeholder1 was the ancestor of ID placeholder2, ID placeholder2 successfully got an award for placeholder3, so you will get reward in ETH for placeholder4!",
        rus : "Ваша собака нулевого поколения ID placeholder1 была предком ID placeholder2, ID placeholder2 успешно вознаграждена за placeholder3, в связи с этим вы получите вознаграждение в эфирах за следующего placeholder3.",
        kor : "",
        jpn : "貴方の0代DOG（ID） placeholder1 はDOG（ID）placeholder2 の祖先として、 placeholder3 賞金当選のplaceholder4ETH収益を貰いました。",
    },
    "earning6" :{
        cn : "您的狗狗 placeholder1 被系统回收，您获得了placeholder2 ETH收益，已转入了您的钱包！",
        en : "As your dog placeholder1 is recycled by the system，you gained ETH for placeholder2, which have been transfer to your wallet successfully.",
        rus : "Так как, ваша placeholder1 перерабатывается системой, вы получили эфир за placeholder2, который был успешно переведен на ваш кошелек.",
        kor : "",
        jpn : "貴方のDOG placeholder1 はシステムにより回収されました。placeholder2 ETH収益をウォレットに入れました。",
    },
    "earning6-1" :{
        cn : "您于 placeholder1 成功遛了placeholder2 只0代狗，获得了 placeholder3 OGC",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "earning7" :{
        cn : "已获得收益",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "earning8" :{
        cn : "查看收益历史记录",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "earning9" :{
        cn : "创世",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "earning10" :{
        cn : "创世狗相当于Hello Dog的股东制，所有狗狗繁殖每只创世狗将分得手续费0.001ETH。创世狗收益详情只显示最近200条。",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "earning11" :{
        cn : "您的创世狗为您带来了 placeholder1 ETH的收益",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "earning12" :{
        cn : "您共有 placeholder1 只0代狗，今天为您带来了 placeholder2 ETH的收益",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "earning13" :{
        cn : "查看0代分红记录",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "earning14" :{
        cn : "0代分红记录",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    /*收益结束*/

    /*提现开始*/
    "extract-tit":{
        cn : "提现记录",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "extract1":{
        cn : "提现",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "extract2":{
        cn : "累积收益：",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "extract3":{
        cn : "可提收益：",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "extract4" : {
        cn : "可遛0代：",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "extract5" : {
        cn : "说明：寄售中、租借中的狗狗不能参与遛狗与分红！",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "extract6":{
        cn : "提取",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "extract7":{
        cn : "提取记录",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "extract8":{
        cn : "0代分红：",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    /*提现结束*/

      /*兑奖开始*/
    "winning-title":{
        cn : "兑奖",
        en : "Redemption",
        rus : "Выкуп",
        kor : "",
        jpn : "受賞",
    },
    "winning0-0":{
        cn : "很遗憾本期没有中奖！",
        en : "Unfortunately, there is no winner in this period!",
        rus : "К сожалению, в этой лотереи нет победителя!",
        kor : "",
        jpn : "残念！今期は当たりませんでした。",
    },
    "winning0-1":{
        cn : "恭喜你中一等奖！",
        en : "Congratulations, you won the first prize!",
        rus : "Поздравляем, вы выиграли первый приз!",
        kor : "",
        jpn : "一等賞おめでとう！",
    },
    "winning0-2":{
        cn : "恭喜你中二等奖！",
        en : "Congratulations, you won the second prize!",
        rus : "Поздравляем, вы выиграли второй приз!",
        kor : "",
        jpn : "ニ等賞おめでとう！",
    },
    "winning0-3":{
        cn : "恭喜你中三等奖！",
        en : "Congratulations, you won the third prize!",
        rus : "Поздравляем, вы выиграли третий приз!",
        kor : "",
        jpn : "三等賞おめでとう！",
    },
    "winning0-4":{
        cn : "恭喜你中四等奖！",
        en : "Congratulations, you won the fourth prize!",
        rus : "Поздравляем, вы выиграли четвертый приз!",
        kor : "",
        jpn : "四等賞おめでとう！",
    },
    "winning0-5":{
        cn : "恭喜你中五等奖！",
        en : "Congratulations, you won the fifth prize!",
        rus : "Поздравляем, вы выиграли пятый приз!",
        kor : "",
        jpn : "五等賞おめでとう！",
    },
    "winning0-6":{
        cn : "恭喜你中六等奖！",
        en : "Congratulations, you won the sixth prize!",
        rus : "Поздравляем, вы выиграли шестой приз!",
        kor : "",
        jpn : "六等賞おめでとう！",
    },
    "winning0-7":{
        cn : "恭喜你中七等奖！",
        en : "Congratulations, you won the seventh prize!",
        rus : "Поздравляем, вы выиграли седьмой приз!",
        kor : "",
        jpn : "七等賞おめでとう！",
    },
    "winning1":{
        cn : "本次最低中奖金额：",
        en : "The minimum amount of the award is:",
        rus : "Минимальная сумма вознаграждения:",
        kor : "",
        jpn : "今期最低賞金金額",
    },
    "winning2":{
        cn : "返回宠物中心",
        en : "Back to the Pet Center.",
        rus : "Вернитесь в Центр питомцев.",
        kor : "",
        jpn : "ペットセンターへ戻る",
    },
    "winning3":{
        cn : "确认兑奖",
        en : "Confirm for Redeem",
        rus : "Подтвердите выкуп.",
        kor : "",
        jpn : "受賞確認",
    },
    "winning4":{
        cn : "兑奖有限期为下期开奖前，逾时将视为放弃，狗狗将轮为下次开奖，兑奖完成后官方将进行回收。",
        en : "You must redeem your prize before the start of next lottery, or your will drop your prize, in this case, your dog will still have chance to win in next lottery. The officials will take back the dog after the award is redeemed.",
        rus : "Вы должны выкупить свой выигрыш до начала следующей лотереи, или ваш шанс потеряет ваш приз, в этом случае у вашей собаки все еще будет шанс выиграть в следующей лотерее. Должностные лица вернут собаку после того, как награда будет погашена.",
        kor : "",
        jpn : "",
    },
   "winning5":{
        cn : "您还没有中奖哦！",
        en : "You haven't won the prize!",
        rus : "Вы не выиграли приз!",
        kor : "",
        jpn : "まだ賞金当たっていませんよ！",
    },
    "winning6":{
        cn : "您的小狗在寄售中，请在宠物中心进行下架！",
        en : "Your dog is sold at auction, please take it off first!",
        rus : "Ваша собака продается на аукционе, пожалуйста, сначала снимите ее!",
        kor : "",
        jpn : "貴方のDOGは売出中です。まず棚を卸してください。",
    },
    "winning7":{
        cn : "您的小狗在租借中，请在宠物中心进行下架！",
        en : "Your dog is rented at auction, please take it off first!	",
        rus : "Ваша собака сдаётся в аренду на аукционе, пожалуйста, снимите ее!",
        kor : "",
        jpn : "貴方のDOGはレンタル中です。まず棚を卸してください。",
    },
    "winning8":{
        cn : "兑奖成功！",
        en : "Successfully redeemed!",
        rus : "Успешно выкуплено!",
        kor : "",
        jpn : "",
    },
    "winning9":{
        cn : "",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "winning10":{
        cn : "",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "winning11":{
        cn : "正在开奖中",
        en : "Playing in the lottery",
        rus : "Разыгрывается в лотерее",
        kor : "",
        jpn : "",
    },
    "winning15":{
        cn : "昵称不能为空！",
        en : "Nicknames cannot be empty!",
        rus : "",
        kor : "",
        jpn : "ニックネームは空けてはいけません！",
    },
    "winning16":{
        cn : "您的昵称超出了合法长度！",
        en : "Your nickname is beyond legal length!",
        rus : "",
        kor : "",
        jpn : "ニックネームの長さは法的規定を超えました！",
    },
    "winning18":{
        cn : "怀孕中",
        en : "During Pregnancy",
        rus : "В течение беремености",
        kor : "",
        jpn : "妊娠中",
    },
    "winning19":{
        cn : "待兑奖",
        en : "Waiting for the redemption",
        rus : "Ожидание выкупа",
        kor : "",
        jpn : "",
    },
    "winning20":{
        cn : "出售中",
        en : "Selling",
        rus : "Продажа",
        kor : "",
        jpn : "売出中",
    },
    "winning21":{
        cn : "租借中",
        en : "Renting",
        rus : "Аренда",
        kor : "",
        jpn : "",
    },
    "winning22":{
        cn : "恭喜 ",
        en : "Congratulations to  ",
        rus : "Поздравления ",
        kor : "",
        jpn : "おめでとうございます",
    },
    "winning23":{
        cn : " 购买了 ",
        en : " Been bought ",
        rus : "Куплено",
        kor : "",
        jpn : "購入しました",
    },
    "winning24":{
        cn : "成为hellodog的创世股东，享受持续分红！",
        en : " and becoming a creative shareholder of hellodog and enjoying a continuous dividend!",
        rus : "",
        kor : "",
        jpn : "",
    },
    /*兑奖结束*/

    /*中奖纪录*/
    "redeem-tit" :{
        cn : "兑奖纪录",
        en : "Redemption Record",
        rus : "Запись о погашении",
        kor : "",
        jpn : "受賞記録",
    },
    "redeem0" :{
        cn : "以下是您的中奖纪录：",
        en : "The following is your winning record:",
        rus : "Ниже приведена запись ваших побед:",
        kor : "",
        jpn : "貴方様の当選記録です。",
    },
    "redeem1" :{
        cn : "<em>您的狗狗 placeholder1 </em> 获得 <em> placeholder2 </em>等奖，您获得了 <em> placeholder3 ETH</em>",
        en : "<em> placeholder1 </em> win <em> placeholder2 </em>prize，and you will get <em> placeholder3 ETH</em>",
        rus : "<em> placeholder1 </ em> выигрывает <em> placeholder2 </ em> приз, и вы получите <em> placeholder3 ETH </ em>",
        kor : "",
        jpn : "<em> placeholder1 </em>等賞獲得<em> placeholder2 </em>、　<em> placeholder3 ETH</em>獲得",
    },
    "redeem2" :{
        cn : "查看兑奖历史记录",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    /*中奖纪录结束*/

    /* 邀请好友开始 */
    "friends1" : {
        cn : "",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "friends2" : {
        cn : "钱包地址",
        en : "Wallet Address",
        rus : "Адрес кошелька",
        kor : "",
        jpn : "ウォレットアドレス",
    },
    "friends3" : {
        cn : "邀请链接",
        en : "Invitation Link",
        rus : "Ссылка для приглашения",
        kor : "",
        jpn : "招待リンク",
    },
    "friends4" : {
        cn : "复制",
        en : "Copy",
        rus : "Копировать",
        kor : "",
        jpn : "コピー",
    },
    "friends5" : {
        cn : "分享邀请链接",
        en : "Share Invitation Link",
        rus : "Поделиться Ссылка для приглашения",
        kor : "",
        jpn : "",
    },
    "friends6" : {
        cn : "当前钱包余额",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "friends7" : {
        cn : "算力",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "friends8" : {
        cn : "领取",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "friends9" : {
        cn : "转账",
        en : "Transfer",
        rus : "",
        kor : "",
        jpn : "",
    },
    "friends10" : {
        cn : "如果算力为X，即代表每天都可以获得X枚OGC",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "friends11" : {
        cn : "如何获得更多算力？",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "friends12" : {
        cn : "邀请一位好友算力(最多邀请30位好友)",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "friends13" : {
        cn : "您的邀请码",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "friends14" : {
        cn : "成功邀请好友并注册钱包保存用户信息，即可增加算力",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "friends15" : {
        cn : "每日进入APP点击领取即可获得OGC",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "friends16" : {
        cn : "转账记录",
        en : "Transfer record",
        rus : "",
        kor : "",
        jpn : "",
    },
    "friends17" : {
        cn : "必须拥有一只狗狗才可进行转账 当前拥有：",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "friends18" : {
        cn : "每只狗每次转账上限是 10 OGC",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    /* 邀请好友结束*/

    /*保存信息*/
    "saveinfo-tit" : {
        cn : "个人中心",
        en : "Personal Center",
        rus : "Персональный центр",
        kor : "",
        jpn : "個人センター",
    },
    "saveinfo0" : {
        cn : "复制成功",
        en : "Successfully copied",
        rus : "Успешно скопировано",
        kor : "",
        jpn : "コピー成功",
    },
    "saveinfo1" : {
        cn : "请输入正确的邮箱",
        en : "Please enter your valid e-mail address.",
        rus : "Пожалуйста, введите ваш действительный адрес электронной почты.",
        kor : "",
        jpn : "正しいメールアドレスを入力してください。",
    },
    "saveinfo2" : {
        cn : "请输入正确的昵称",
        en : "Please enter correct nickname.",
        rus : "Введите правильный псевдоним.",
        kor : "",
        jpn : "正しいニックネームを入力してください。",
    },
    "saveinfo3" : {
        cn : "请同意用户协议",
        en : "Please accept the user agreement.",
        rus : "Примите пользовательское соглашение",
        kor : "",
        jpn : "利用規約を同意してください。",
    },
    "saveinfo4" : {
        cn : "保存成功",
        en : "Saved successfully",
        rus : "Успешно сохранено",
        kor : "",
        jpn : "保存成功",
    },
    "saveinfo5" : {
        cn : "您的HelloDog帐户",
        en : "Your HelloDog account",
        rus : "Ваша учетная запись HelloDog",
        kor : "",
        jpn : "貴方のHellodogアカウント",
    },
    "saveinfo6" : {
        cn : "钱包地址：",
        en : "Wallet Address",
        rus : "Адрес кошелька",
        kor : "",
        jpn : "ウォレットアドレス",
    },
    "saveinfo7" : {
        cn : "复制",
        en : "Copy",
        rus : "Копировать",
        kor : "",
        jpn : "コピー",
    },
    "saveinfo8" : {
        cn : "电子邮件",
        en : "E-mail Address",
        rus : "Адрес электронной почты",
        kor : "",
        jpn : "メール",
    },
    "saveinfo9" : {
        cn : "昵称",
        en : "Nickname",
        rus : "Псевдоним",
        kor : "",
        jpn : "ニックネーム",
    },
    "saveinfo10" : {
        cn : "同意hello dog 服务条款",
        en : "Accept the service terms of HelloDog",
        rus : "Принять условия обслуживания HelloDog",
        kor : "",
        jpn : "HelloDogのサービス条項を同意する",
    },
    "saveinfo11" : {
        cn : "确保保存您的MetaMask登录信息和帐户恢复详细信息！如果您失去它，我们不能帮助您恢复访问。",
        en : "Make sure to save your MetaMask login information and account recovery details! We can’t help you regain access, if you lose it.",
        rus : "Обязательно сохраните свои данные о регистрации в MetaMask и сведения о восстановлении аккаунта! Мы не можем помочь вам восстановить доступ, если вы их потеряете.",
        kor : "",
        jpn : "Metamask登録情報とアカウント回復情報を保存してください。関連情報を失くしますと、アクセスできなくなります。",
    },
    "saveinfo12" : {
        cn : "保存账户信息",
        en : "Save account info",
        rus : "Сохранить учетную запись",
        kor : "",
        jpn : "アカウント情報保存",
    },
    "saveinfo13" : {
        cn : "请输入您的邮箱",
        en : "Please enter valid e-mail address.",
        rus : "Пожалуйста, введите действующий адрес электронной почты.",
        kor : "",
        jpn : "メールアドレスを入力してください。",
    },
    "saveinfo14" : {
        cn : "请输入您的昵称",
        en : "Please enter correct nickname.",
        rus : "Введите правильный псевдоним.",
        kor : "",
        jpn : "ニックネームを入力してください。",
    },
    "saveinfo15" : {
        cn : "请输入邀请码",
        en : "Please enter the right nickname.",
        rus : "",
        kor : "",
        jpn : "ニックネームを入力してください。",
    },
    "saveinfo16" : {
        cn : "请输入手机号码",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "saveinfo17" : {
        cn : "请输入手机验证码",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "saveinfo18" : {
        cn : "保存",
        en : "Update info",
        rus : "",
        kor : "",
        jpn : "。",
    },
    "saveinfo19" : {
        cn : "输入的手机号码不正确",
        en : "",
        rus : "",
        kor : "",
        jpn : "。",
    },
    "saveinfo20" : {
        cn : "输入验证码不正确",
        en : "",
        rus : "",
        kor : "",
        jpn : "。",
    },
    /*保存信息结束*/

    /* 反馈开始 */
    "feedback-tit": {
        cn : "反馈",
        en : "Feedback",
        rus : "Обратная связь",
        kor : "",
        jpn : "",   
    },
    "feedback1": {
        cn : "狗狗ID：",
        en : "Dog Id：",
        rus : "Идентификатор собаки:",
        kor : "",
        jpn : "",   
    },
    "feedback2": {
        cn : "交易hash：",
        en : "Transaction hash：",
        rus : "Хеширование транзакций:",
        kor : "",
        jpn : "", 
    },
    "feedback3": {
        cn : "反馈信息：",
        en : "Feedback information：",
        rus : "Информация об обратной связи:",
        kor : "",
        jpn : "",  
    },
    "feedback4": {
        cn : "反馈内容不能为空",
        en : "The feedback cannot be empty",
        rus : "Обратная связь не может быть пустой",
        kor : "",
        jpn : "",  
    },
    /* 反馈结束 */

    /* 个人中心开始 */
    "myself-tit" : {
        cn : "个人中心",
        en : "Personal Center",
        rus : "Персональный центр",
        kor : "",
        jpn : "個人センター",
    },
    "myself1": {
        cn : "拥有狗狗",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself2": {
        cn : "余额",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "myself3": {
        cn : "我的钱包",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself4": {
        cn : "玩法",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself5": {
        cn : "设置",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself6": {
        cn : "用户名",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself7": {
        cn : "邮箱地址",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself8": {
        cn : "邀请码",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself9": {
        cn : "保存",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself10": {
        cn : "对方钱包地址",
        en : "Other's wallet address",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself11": {
        cn : "账户剩余数量",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself12": {
        cn : "填写数量",
        en : "Amount",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself13": {
        cn : "全部数量",
        en : "Total",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself14": {
        cn : "确认转账",
        en : "Confirm transfer",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself15": {
        cn : "获取验证码",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself16": {
        cn : "请输入邀请码（<em>可选填</em>）",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself17": {
        cn : "手机号码",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself18": {
        cn : "验证码",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    "myself19": {
        cn : "获取验证码",
        en : "",
        rus : "",
        kor : "",
        jpn : "",   
    },
    /* 个人中心结束 */
    

    /*alert 提示语 */
    "alert0" : {
        cn : "暂无数据！",
        en : "No data!",
        rus : "Нет данных!",
        kor : "",
        jpn : "データが見つかりません。",
    },
    "alert1" : {
        cn : "操作成功，矿工正在拼命挖矿中，请在宠物中心右下方查看交易情况！",
        en : "The operation is successful.Please wait patietly.",
        rus : "",
        kor : "",
        jpn : "操作は成功しました。暫くお待ちください。",
    },
    "alert2" : {
        cn : "钱包余额不足，请到数字货币交易所充值或加官方qq群:547351294找管理员代充",
        en : "Insufficient balance of your wallet!",
        rus : "",
        kor : "",
        jpn : "ウォレットの残高は足りませんでした。",
    },
    "alert3" : {
        cn : "开始繁殖了，矿工正在拼命挖矿中，请在宠物中心右下方查看交易情况！",
        en : "Start to reproduce.Please wait patietly.",
        rus : "",
        kor : "",
        jpn : "繁殖が開始しました。暫くお待ちください。",
    },
    "alert4" : {
        cn : "该狗狗已中奖，禁止所有的操作！",
        en : "The dog has won the prize, all operations are prohibited!",
        rus : "Собака выиграла приз, все операции запрещены!",
        kor : "",
        jpn : "",
    },
    "alert5" : {
        cn : "执行失败，狗狗的状态正在发生改变或钱包余额不足以支付gas，请稍后再试！",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert6" : {
        cn : "接收地址错误",
        en : "Receive address error",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert7" : {
        cn : "复制成功",
        en : "Successfully copied",
        rus : "Успешно скопировано",
        kor : "",
        jpn : "コピー成功",
    },
    "alert8" : {
        cn : "操作成功",
        en : "Successful operation!",
        rus : "Успешная операция!",
        kor : "",
        jpn : "操作は成功しました",
    },
    "alert9" : {
        cn : "今日无可领取金额！",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert10" : {
        cn : "领取失败请重试",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert11" : {
        cn : "数据异常请重试",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert12" : {
        cn : "验证码发送成功",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert13" : {
        cn : "钱包余额需大于1 OGC才可以转账",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert14" : {
        cn : "超出最大转账限额！",
        en : "Exceeded maximum transfer limit",
        rus : "",
        kor : "",
        jpn : "最大振り替え限度を超過しました",
    },
    "alert15" : {
        cn : "余额不足！",
        en : "Insufficient balance",
        rus : "",
        kor : "",
        jpn : "残高不足",
    },
    "alert16" : {
        cn : "操作失败请重试！",
        en : "Operation failed Please try again",
        rus : "",
        kor : "",
        jpn : "すみません、もう一度お試しください　",
    },
    "alert17" : {
        cn : "请输入对方钱包地址！",
        en : "Please enter the address of your partner's wallet",
        rus : "",
        kor : "",
        jpn : "相手の財布アドレスをご入力しください",
    },
    "alert18" : {
        cn : "请输入转账金额！",
        en : "Please enter the transfer amount",
        rus : "",
        kor : "",
        jpn : "振り替え金額をご入力しください",
    },
    "alert19" : {
        cn : "说明:钱包余额需大于1 OGC才可以转账",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert20" : {
        cn : "期号不能为空",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert21" : {
        cn : "钱包未解锁，请先在钱包界面进行解锁！",
        en : "Your wallet is not unlocked. Please unlock your wallet first!",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert22" : {
        cn : "请先登录钱包",
        en : "Please login to wallet",
        rus : "",
        kor : "",
        jpn : "まずウォレットの登録をお願いします。",
    },
    "alert23" : {
        cn : "未选择配偶",
        en : "No spouse selected..",
        rus : "Супруг не выбран.",
        kor : "",
        jpn : "相手を選択していません。",
    },
    "alert24" : {
        cn : "生育费异常，请稍后再试！",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert25" : {
        cn : "选择成功！",
        en : "Been successfully chosen",
        rus : "Успешно выбрано!",
        kor : "",
        jpn : "",
    },
    "alert26" : {
        cn : "敬请期待",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert27" : {
        cn : "可提现金额必须大于0",
        en : "The cashable amount must be greater than 0",
        rus : "",
        kor : "",
        jpn : "キャッシュ可能金額は0より大きくなければなりません",
    },
    "alert28" : {
        cn : "遛狗成功，获得了 placeholder1 OGC",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert29" : {
        cn : "",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "alert30" : {
        cn : "",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "9999" : {
        cn : "请求失败",
        en : "Request failed",
        rus : "",
        kor : "",
        jpn : "リクエストが失敗しました",
    },
    "9995" : {
        cn : "操作非法",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "9996" : {
        cn : "参数token异常",
        en : "Incorrect Parameter token ",
        rus : "",
        kor : "",
        jpn : "パラメータトークンが異常です　",
    },
    "9997" : {
        cn : "缺少参数",
        en : "Missing parameters",
        rus : "",
        kor : "",
        jpn : "パラメータが欠けている",
    },
    "9998" : {
        cn : "错误参数",
        en : "Wrong parameters",
        rus : "",
        kor : "",
        jpn : "パラメータが間違っています",
    },
    "3006" : {
        cn : "生成订单号异常",
        en : "The order number goes wrong",
        rus : "",
        kor : "",
        jpn : "注文番号が異常です",
    },
    "1000" : {
        cn : "短信已关闭",
        en : "SMS is closed",
        rus : "",
        kor : "",
        jpn : "ＳＭＳ機能が閉じられている",
    },
    "1001" : {
        cn : "手机号码为空",
        en : "Phone number is empty",
        rus : "",
        kor : "",
        jpn : "電話番号が存在しません",
    },
    "1002" : {
        cn : "手机号非法",
        en : "Illegal phone number",
        rus : "",
        kor : "",
        jpn : "不正な電話番号です",
    },
    "1003" : {
        cn : "请求过于频繁",
        en : "Requests are too frequent",
        rus : "",
        kor : "",
        jpn : "頻繁にリクエストしてすみません",
    },
    "1004" : {
        cn : "手机号已经被使用过",
        en : "Used phone number ",
        rus : "",
        kor : "",
        jpn : "電話番号が既に使用されている",
    },
    "1005" : {
        cn : "当前手机号已超过今天最大发送次数",
        en : "The current phone number has exceeded the maximum number of send today",
        rus : "",
        kor : "",
        jpn : "この携帯電話番号が今日の最大送信数を超えました",
    },
    "1006" : {
        cn : "当前IP已超过今天最大发送次数",
        en : "The current IP has exceeded the maximum number of send today",
        rus : "",
        kor : "",
        jpn : "このIPが今日の最大送信数を超えました",
    },
    "1007" : {
        cn : "短信验证码为空",
        en : "SMS verification code is empty",
        rus : "",
        kor : "",
        jpn : "SMS認証コードがありません",
    },
    "1008" : {
        cn : "手机验证码不存在",
        en : "SMS verification code does not exist",
        rus : "",
        kor : "",
        jpn : "電話番号認証コードが存在しません",
    },
    "1009" : {
        cn : "账户被禁用",
        en : "The account is banned",
        rus : "",
        kor : "",
        jpn : "アカウントは無効になっています",
    },
    "1010" : {
        cn : "发送手机验证码异常",
        en : "SMS verification code goes wrong",
        rus : "",
        kor : "",
        jpn : "電話番号認証が異常です　",
    },
    "1011" : {
        cn : "登录异常",
        en : "Login goes wrong",
        rus : "",
        kor : "",
        jpn : "ログイン出来ない",
    },
    "1012" : {
        cn : "用户已注册",
        en : "user already exists",
        rus : "",
        kor : "",
        jpn : "ユーザー名は既に存在しています",
    },
    "1200" : {
        cn : "用户不存在",
        en : "user does not exist",
        rus : "",
        kor : "",
        jpn : "ユーザー名は存在しません",
    },
    "1201" : {
        cn : "获取用户主要信息失败",
        en : "Failed to get user's major information",
        rus : "",
        kor : "",
        jpn : "ユーザーの主な情報を取得できません",
    },
    "1202" : {
        cn : "获取用户详细信息失败",
        en : "Failed to get user's detail information",
        rus : "",
        kor : "",
        jpn : "ユーザーの詳しい情報を取得できません",
    },
    "1203" : {
        cn : "用户未登录",
        en : "User is not logged in",
        rus : "",
        kor : "",
        jpn : "ユーザーはまた登録しません",
    },
    "1204" : {
        cn : "用户更新失败",
        en : "Fail in Updating",
        rus : "",
        kor : "",
        jpn : "更新に失敗しました",
    },
    "1205" : {
        cn : "请填写真实姓名",
        en : "Please fill in your real name",
        rus : "",
        kor : "",
        jpn : "お名前を入力してください",
    },
    "1206" : {
        cn : "身份证号码为空",
        en : "Empty ID number",
        rus : "",
        kor : "",
        jpn : "ID番号がありません",
    },
    "1207" : {
        cn : "身份证正面照为空",
        en : "Front photo of ID card is empty",
        rus : "",
        kor : "",
        jpn : "IDカードの正面写真がありません",
    },
    "1208" : {
        cn : "手持身份证照为空",
        en : "Hand-held photo of ID card is empty",
        rus : "",
        kor : "",
        jpn : "IDカードを持っている写真がありません",
    },
    "1209" : {
        cn : "身份证反面照为空",
        en : "Rear photo of ID card is empty",
        rus : "",
        kor : "",
        jpn : "IDカードのバック写真がありません",
    },
    "1210" : {
        cn : "联系方式为空",
        en : "Contact information is empty",
        rus : "",
        kor : "",
        jpn : "連絡先がありません",
    },
    "1211" : {
        cn : "昵称已存在",
        en : "Nickname already exists",
        rus : "",
        kor : "",
        jpn : "ニックネームは既に存在します",
    },
    "1212" : {
        cn : "邀请码不存在",
        en : "Invitation code does not exist",
        rus : "",
        kor : "",
        jpn : "招待コードは存在しません",
    },
    "1213" : {
        cn : "已填写过邀请码",
        en : "Used invitation number",
        rus : "",
        kor : "",
        jpn : "招待コードは既に使用しました",
    },
    "1214" : {
        cn : "邀请码发放失败",
        en : "Failed to send invitation number",
        rus : "",
        kor : "",
        jpn : "招待コードの送信に失敗しました",
    },
    "1215" : {
        cn : "优惠券不存在",
        en : "Coupon does not exist",
        rus : "",
        kor : "",
        jpn : "クーポンがありません",
    },
    "1216" : {
        cn : "优惠券不能兑换",
        en : "Coupon cannot be exchanged",
        rus : "",
        kor : "",
        jpn : "クーポンが使用できません",
    },
    "1217" : {
        cn : "优惠券兑换失败",
        en : "Coupon exchange failed",
        rus : "",
        kor : "",
        jpn : "クーポンが使用できません",
    },
    "1218" : {
        cn : "优惠券已过期",
        en : "Coupon expired",
        rus : "",
        kor : "",
        jpn : "期限切れクーポン",
    },
    "1219" : {
        cn : "两次密码不一样",
        en : "The password and confirmation password are different",
        rus : "",
        kor : "",
        jpn : "二回のパスワードが異なっている",
    },
    "1220" : {
        cn : "密码错误",
        en : "Wrong password",
        rus : "",
        kor : "",
        jpn : "パスワードか間違っています",
    },
    "1221" : {
        cn : "请实名认证",
        en : "Real name certification",
        rus : "",
        kor : "",
        jpn : "実名認証",
    },
    "1222" : {
        cn : "用户已认证",
        en : "Verified user",
        rus : "",
        kor : "",
        jpn : "認証しました",
    },
    "1223" : {
        cn : "用户名过长",
        en : "Username is too long",
        rus : "",
        kor : "",
        jpn : "ユーザー名が長すぎます",
    },
    "1224" : {
        cn : "邀请码不存在",
        en : "Invitation code does not exist",
        rus : "",
        kor : "",
        jpn : "招待コードは存在しません",
    },
    "1225" : {
        cn : "每日回报已经领取过",
        en : "Daily return has been received",
        rus : "",
        kor : "",
        jpn : "毎日の奨励をもうもらいました",
    },
    "1226" : {
        cn : "邀请人注册IP地址重复",
        en : "The registered IP address of the invitee is duplicated",
        rus : "",
        kor : "",
        jpn : "",
    },
    "1227" : {
        cn : "每日回报今日无可领金额",
        en : "Daily return can't be received",
        rus : "",
        kor : "",
        jpn : "今日、毎日の奨励がありません",
    },
    "1228" : {
        cn : "转账源账户不存在",
        en : "The transfer source account does not exist",
        rus : "",
        kor : "",
        jpn : "振り替えのソースアカウントが存在しません",
    },
    "1229" : {
        cn : "转账目标账户不存在",
        en : "The transfer target account does not exist",
        rus : "",
        kor : "",
        jpn : "振り替えの相手アカウントが存在しません",
    },
    "1230" : {
        cn : "当前不可领取",
        en : "Сurrently unavailable to draw",
        rus : "",
        kor : "",
        jpn : "受け取りができない",
    },
    "1231" : {
        cn : "邮箱非法",
        en : "Incorrect e-mail address",
        rus : "",
        kor : "",
        jpn : "電子メールが間違っている",
    },
    "1232" : {
        cn : "钱包地址为空",
        en : "Wallet Address is empty",
        rus : "",
        kor : "",
        jpn : "財布アドレスがありません",
    },
    "1233" : {
        cn : "OGC数量小于转账最小限额",
        en : "Number of OGC is less than the transfer limit",
        rus : "",
        kor : "",
        jpn : "OGC数量は振り替え限度未満です",
    },
    "1234" : {
        cn : "不能给自己转账",
        en : "Self-transfer is forbidden",
        rus : "",
        kor : "",
        jpn : "自分へ振り替えができません",
    },
    "1235" : {
        cn : "账户下没有狗狗，不能转账",
        en : "There is no dog under the account and no transfer can be made",
        rus : "",
        kor : "",
        jpn : "口座の下に犬がいないため、譲渡することはできません",
    },
    "1236" : {
        cn : "缺少签名参数",
        en : "Missing signature parameters",
        rus : "",
        kor : "",
        jpn : "署名パラメータがありません",
    },
    "1300" : {
        cn : "狗狗不存在",
        en : "Dog does not exist",
        rus : "",
        kor : "",
        jpn : "犬がいません",
    },
    "1301" : {
        cn : "狗狗名过长",
        en : "Dog's nickname is too long",
        rus : "",
        kor : "",
        jpn : "犬の名が長すぎます",
    },
    "1302" : {
        cn : "狗狗不属于您，您无权修改",
        en : "You are not allowed to modify the dog which does not belong to you",
        rus : "",
        kor : "",
        jpn : "",
    },
    "1400" : {
        cn : "调用开奖失败",
        en : "Failed to call the lottery",
        rus : "",
        kor : "",
        jpn : "宝くじに失敗しました",
    },
    "1401" : {
        cn : "开奖信息不存在",
        en : "Drawing a lottery information does not exist",
        rus : "",
        kor : "",
        jpn : "宝くじ情報がありません",
    },
    "1402" : {
        cn : "未中奖",
        en : "Losing lottery",
        rus : "",
        kor : "",
        jpn : "宝くじに当たらない",
    },
    "1403" : {
        cn : "已兑过奖",
        en : "もう奨励を受け取りました",
        rus : "",
        kor : "",
        jpn : "Cashed out lottery",
    },
    "1500" : {
        cn : "下注的球队为空",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "1501" : {
        cn : "下注金额非法",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },

    "1502" : {
        cn : "下注场次为空",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "1503" : {
        cn : "下注的比赛结果非法",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "1504" : {
        cn : "竞猜类型非法",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "1505" : {
        cn : "下注的球队不存在",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "1506" : {
        cn : "OGC余额不足",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "1507" : {
        cn : "下注的比赛不存在",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "1511" : {
        cn : "前不可下注",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },

    "1512" : {
        cn : "已封盘",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },

    "1303" : {
        cn : "您今日无可遛的狗狗",
        en : "No dog need to be walked today",
        rus : "",
        kor : "",
        jpn : "今日は犬を散歩させる必要はありません",
    },
    "1304" : {
        cn : "您今日已遛过狗狗",
        en : "You have walked the dog today",
        rus : "",
        kor : "",
        jpn : "もう犬を散歩させました",
    },
    "1305" : {
        cn : "插入遛狗信息失败",
        en : "Fail in loading information",
        rus : "",
        kor : "",
        jpn : "情報のロードに失敗しました",
    },
    "1306" : {
        cn : "暂未开启遛狗功能",
        en : "Walk-the-dog function is not turned on yet",
        rus : "",
        kor : "",
        jpn : "犬を散歩させる機能はまたオープンしません",
    },
    "1237" : {
        cn : "OGC转账数量达到今日上限",
        en : "The OTC transfer number has reached today's upper limit ",
        rus : "",
        kor : "",
        jpn : "今日の振り替えは上限に達する",
    },

    
    
    //钱包
    beginTit : {
        cn : '创建钱包',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    beginTit0 : {
        cn : '设置钱包密码',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    beginTit1 : {
        cn : '马上开始',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    beginTit2 : {
        cn : 'HelloDog钱包不但是一个存储您的加密收藏品和以太币的绝佳工具，而且也是登录您的所有dapp的万能钥匙。',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    beginTit3 : {
        cn : '创建新钱包',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    beginTit4 : {
        cn : '导入现有钱包',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    beginTit5 : {
        cn : '正在创建钱包...',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    beginTit6 : {
        cn : '创建钱包失败，请重试',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    beginTit7 : {
        cn : '提示：创建钱包成功后，请第一时间进入个人中心->我的钱包->备份我的私钥 菜单中将您的私钥进行备份，如私钥丢失，您的账户将永远无法找回，您将面临财产损失！',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit : {
        cn : '导入钱包',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit0 : {
        cn : '输入您的密码',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit1 : {
        cn : '输入的私钥错误',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit2 : {
        cn : '输入的密码不相同',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit3 : {
        cn : '已复制',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit4 : {
        cn : '导入钱包',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit5 : {
        cn : '您必须退出此钱包后才可能使用其他钱包',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit6 : {
        cn : '如果您以后会重新登录此钱包，请务必备份好您的私钥。',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit7 : {
        cn : '输入钱包密码',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit8 : {
        cn : '确认钱包密码',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit9 : {
        cn : '输入您的私钥',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit10 : {
        cn : '请输入6位密码',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit11 : {
        cn : '输入6位确认密码',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit12 : {
        cn : '例如：0x489edec..',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    importTit13 : {
        cn : '导入',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWalletTit : {
        cn : '我的钱包',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet0 : {
        cn : '复制到粘贴板',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet1 : {
        cn : '复制地址',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet2 : {
        cn : '分享地址',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet3 : {
        cn : '输入您的密码',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet4 : {
        cn : '请输入金额',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet5 : {
        cn : '余额不足',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet6 : {
        cn : '请重新登录钱包',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet7 : {
        cn : '接收地址错误',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet8 : {
        cn : '支付以太币',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet9 : {
        cn : '确定',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet10 : {
        cn : '操作成功！',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet11 : {
        cn : '支付失败，请稍后重试',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet12 : {
        cn : '钱包地址',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet13 : {
        cn : '输入当前密码',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet14 : {
        cn : '密码错误',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet15 : {
        cn : '输入新密码',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet16 : {
        cn : '输入密码打开钱包',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet17 : {
        cn : '请先复制秘钥并备份好',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet18 : {
        cn : '网页版暂不支持，请在app内打开',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet19 : {
        cn : '接收以太币',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet20 : {
        cn : '以太币合计',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet21 : {
        cn : 'HelloDog',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet22 : {
        cn : '备份我的私钥',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet23 : {
        cn : '设定密码',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet24 : {
        cn : '使用其他钱包',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet25 : {
        cn : '退出',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet26 : {
        cn : '取消',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet27 : {
        cn : '备份秘钥',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet28 : {
        cn : '手动备份',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet29 : {
        cn : '建议您手动复制私钥并粘贴到安全处保存',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet30 : {
        cn : '请不要将此信息透露给别人。这是您的私密密码。',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet31 : {
        cn : '我的私钥',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet32 : {
        cn : '完成',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet33 : {
        cn : '此公共地址是用于接收以太币',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet34 : {
        cn : '发送您的钱包地址给好友是安全的',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet35 : {
        cn : '在下方表格中输入收款钱包地址和发送金额便可以发送以太币给其他钱包',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet36 : {
        cn : '扫描收款人的二维码',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet37 : {
        cn : '或',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    myWallet38 : {
        cn : '输入收款钱包地址',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },

    ogclist0 : {
        cn : '转账记录',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    ogclist1 : {
        cn : '转出',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    ogclist2 : {
        cn : '转入',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    ogclist3 : {
        cn : '钱包地址',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    ogclist4 : {
        cn : '类型',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    ogclist5 : {
        cn : 'OGC',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },
    ogclist6 : {
        cn : '时间',
        en : '',
        rus : '',
        kor : '',
        jpn : '',
    },

    /*交易记录*/
    "translist-tit" : {
        cn : "交易记录",
        en : "Transactions record",
        rus : "История транзакций",
        kor : "",
        jpn : "取引記録",
    },
    "translist0" : {
        cn : "以下是您所请求的交易记录，请记住，一旦交易进入区块链，网页程序需要几分钟才能收到更新，所以请您耐心等待。",
        en : "The following is the transaction history that you requested, please bear in mind that once the transaction enters the blockchain, the webpage program needs a few minutes to receive the update, so please wait patiently.",
        rus : "Ниже приведена история транзакций, которую вы запрашивали, пожалуйста, помните, что после того, как транзакция войдет в блокчейн, программе веб-страницы потребуется несколько минут, чтобы получить обновление, поэтому, пожалуйста, проявите терпение.",
        kor : "",
        jpn : "下記は貴方が申し込んだ取引記録になります。取引はブロックチェーンに入りますと、更新するまで少し時間をかかりますので、暫くお待ちください。",
    },
    "translist1" : {
        cn : "查看详情",
        en : "View the details",
        rus : "Просмотреть детали",
        kor : "",
        jpn : "詳細確認",
    },
    "translist2" : {
        cn : "您 赠送Dog:<em> placeholder1 </em>给 placeholder2 ",
        en : "You donate Dog:<em> placeholder1 </em> give placeholder2",
        rus : "Вы дарите собаку: <em> placeholder1 </ em> даёт placeholder2",
        kor : "",
        jpn : "貴方はDOG<em> placeholder1 </em>をxxさんにプレゼントします。placeholder2",
    },
    "translist3" : {
        cn : "placeholder1 赠送Dog:<em> placeholder2 </em>给您",
        en : "placeholder1 donates dog:<em> placeholder2 </em> to you.",
        rus : "You donate Dog:<em> placeholder1 </em> to placeholder2",
        kor : "",
        jpn : "xxさんからプレゼントのDOG<em> placeholder2 </em>が届きました。",
    },
    "translist4" : {
        cn : "placeholder1 租借您的Dog:<em> placeholder2 </em>，您获得了<em> placeholder3 ETH</em>",
        en : "placeholder1 is renting your dog:<em> placeholder2 </em> rented,   you received <em> placeholder3 ETH</em>",
        rus : "placeholder1 арендует вашу собаку: <em> placeholder2 </ em> взял в аренду, вы получили <em> placeholder3 ETH </ em>",
        kor : "",
        jpn : "DOGがレンタルされplaceholder1、<em> placeholder3 ETH</em>を獲得しました。",
    },
    "translist5" : {
        cn : "您 租借placeholder1 的Dog:<em> placeholder2 </em>，您消耗了<em> placeholder3 ETH</em>",
        en : "You rent placeholder1's <em> placeholder2 </em>，you consumed <em> placeholder3 ETH</em>",
        rus : "Вы арендуете у placeholder1 <em> placeholder2 </ em>, вы потребляете <em> placeholder3 ETH </ em>",
        kor : "",
        jpn : "placeholder1 DOG<em> placeholder2 </em>をレンタルしましたので、<em> placeholder3 ETH</em>を使いました。",
    },
    "translist6" : {
        cn : "placeholder1 购买您的Dog:<em> placeholder2 </em>，您获得了<em> placeholder3 ETH</em>",
        en : "placeholder1 purchased your dog <em> placeholder2 </em>， you received <em> placeholder3 ETH</em>",
        rus : "placeholder1 купил вашу собаку <em> placeholder2 </ em>, вы получили <em> placeholder3 ETH </ em>",
        kor : "",
        jpn : "placeholder1 DOG <em> placeholder2 </em>が購入され、<em> placeholder2 </em>を獲得しました。",
    },
    "translist7" : {
        cn : "您 购买 placeholder1 的Dog:<em> placeholder2 </em>，您消耗了<em> placeholder3 ETH</em>",
        en : "You bought placeholder1's dog <em> placeholder2 </em>, you consumed <em> placeholder3 ETH</em>  ",
        rus : "Вы купили placeholder1's dog <em> placeholder2 </ em>, вы потребляли <em> placeholder3 ETH </ em>",
        kor : "",
        jpn : "DOG<em> placeholder2 </em>を購入しましたので、placeholder1<em> placeholder3 ETH</em>を使いました。",
    },
    "translist8" : {
        cn : "",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    /*交易记录结束*/

    "cup1" : {
        cn : "小组赛",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "cup2" : {
        cn : "竞猜冠军",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "cup3" : {
        cn : "竞猜记录",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "cup4" : {
        cn : "小组赛记录",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "cup5" : {
        cn : "冠军记录",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "cup6" : {
        cn : "世界杯",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "cup7" : {
        cn : "押注成功",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "cup8" : {
        cn : "押注金额必须大于或等于1个OGC",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "cup9" : {
        cn : "OGC余额不足",
        en : "",
        rus : "",
        kor : "",
        jpn : "",
    },
    "cup10" : {
        cn : "请先登录钱包",
        en : "Please login to wallet",
        rus : "",
        kor : "",
        jpn : "まずウォレットの登録をお願いします。",
    },

    /*page*/
    "page0":{
        cn : '共<span class="num-total"> placeholder1 </span>条，  共 <span class="num-total"> placeholder2 </span>页，',
        en : 'In total<span class="num-total"> placeholder1 </span>items，   <span class="num-total"> placeholder2 </span>pages,',
        rus : "Всего <span class = \"num-total\"> placeholder1 </span> элементов, всего <span class = \"num-total\"> placeholder2 </span> страниц",
        kor : "총 <span class=\"num-total\"> placeholder1 </span>개， 총 <span class=\"num-total\"> placeholder2 </span>페이지",
        jpn : '合計<span class="num-total"> placeholder1 </span>項目，  合計 <span class="num-total"> placeholder2 </span>ページ',
     },
     "page1" : {
         cn : "到第",
         en : "to the",
         rus : "К",
         kor : "이동",
         jpn : "",
     },
     "page2" : {
         cn : "页",
         en : "page",
         rus : "Странице",
         kor : "페이지",
         jpn : "ページ",
     },
     /*page 结束*/
}